### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by oheinonen** [tommijuslin/tiralabra#1]
Latasin projektin koneelleni 3.12. klo 15. 

Selkeä repositorio ja projekti vertaisarvioitavaksi. Koodissa käytetty selkeää nimeämistä funktioille ja muuttujille sekä kommentointia on koodin joukossa hyvin. Koodi on myös jaettu asiaankuuluvasti eri kansioihin ja tiedostoihin. Dokumentaatio sisältää kaiken olennaisen kompaktissa muodossa - loppupalautukseen varmaan hyvä lisätä vielä luokkakaaviot. Myös Damerau-Levenshteinin etäisyys sekä Trie-tietorakenne kannattanee avata esimerkkien / kuvien avulla, sillä ne eivät välttämättä ole kaikille tuttuja.

Ohjelman suorittaminen toimii kätevästi komentoriviltä. Annetuista komennoista mietin, että onko käyttäjälle luotu ominaisuus editoinitetäisyyden laskemisesta tarpeellinen? Sanan lisääminen on varmasti hyvä ominaisuus. Yksi asia joka tuli mieleen liittyy virheellisesti kirjoitetun sanan korjaamiseen, kun sana kuitenkin löytyy sanastosta. Nyt esimerkiksi lause *god morning* jää korjaamatta — olisiko sanastosta löytyville sanoille järkevä katsoa vaihtoehtoja? Voi olla että tämä kuitenkin monimutkaistaa asioita liikaa. 

Joka tapauksessa ohjelma toimii hyvin, ja värit ovat hyvä lisä korjauksiin!

**Comment by tjuslin** [comment]
Kiitos vertaisarvioinnista!

Arvioitiin toistemme projektit näköjään juuri samaan aikaan :D

Olet oikeassa, editointietäisyyden laskeminen ei ole ollenkaan tarpeellinen käyttäjän näkökulmasta. Se on lähinnä jäänyt roikkumaan valikkoon projektin alkuviikoista. Hyvä huomio!

Sanan lisääminenkin on tällä hetkellä aika turha. Sanaa ei edes lisätä itse sanastotiedostoon ja sitten pitäisi miettiä, miten suuri painoarvo (frekvenssi) lisätyille sanoille tulisi antaa.

Tuo mainitsemasi tilanne, missä sanat ovat periaatteessa kirjoitettu oikein mutta kontekstin huomioon ottaen selvästi väärin, on häirinnyt itseänikin. Tykkäsin ratkaisustasi ja se toimi hyvin joissain tilanteissa, mutta törmäsin lopuksi ongelmiin, kuten vertaisarvioinnissani mainitsin. Ideana on antaa käyttäjälle mahdollisuus valita korjausvaihtoehdoista sopivin. Tekstikäyttöliittymä tekee tästä aika kankeaa, mutta ehkä vaan yksinkertaisesti listaan vaikka top 5 vaihtoehdot frekvenssin perusteella.
